#import "CPSSettings.h"
@implementation CPSSettingsController
- (instancetype)init{return [super initWithStyle:UITableViewStyleInsetGrouped];}
- (void)viewDidLoad{[super viewDidLoad];self.title=@"CarPlay Split";}
- (void)viewWillAppear:(BOOL)animated{[super viewWillAppear:animated];[self.tableView reloadData];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)v{return 4;}
- (NSInteger)tableView:(UITableView *)v numberOfRowsInSection:(NSInteger)s{return s==0?1:s==1?3:s==2?2:5;}
- (NSString *)tableView:(UITableView *)v titleForHeaderInSection:(NSInteger)s{return @[ @"CarPlay Split",CPST(@"Tự động",@"Automatic"),CPST(@"Giao diện",@"Appearance"),CPST(@"Thông tin & chẩn đoán",@"Information & diagnostics") ][s];}
- (NSString *)tableView:(UITableView *)v titleForFooterInSection:(NSInteger)s{
 if(s==0)return CPST(@"Mở Split và chọn ứng dụng trực tiếp trong từng khung trên màn hình CarPlay.",@"Open Split and choose apps directly in each pane on the CarPlay display.");
 if(s==1)return CPST(@"Ngắt kết nối: chờ 12 giây; kết nối lại sẽ hủy đóng. Chỉ đóng app Split quản lý, bỏ qua app đang dùng trên iPhone. Đóng hẳn app sẽ dừng nhạc và có thể mất dữ liệu chưa lưu.",@"Disconnect: wait 12 seconds; reconnecting cancels closing. Only Split-managed apps are closed; the foreground phone app is protected. Closing stops audio and may lose unsaved work.");return nil;
}
- (UITableViewCell *)tableView:(UITableView *)v cellForRowAtIndexPath:(NSIndexPath *)p{
 UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil];NSString *key=nil;
 if(p.section==0){c.textLabel.text=CPST(@"Bật CarPlay Split",@"Enable CarPlay Split");key=@"enabled";}
 if(p.section==1){c.textLabel.text=@[CPST(@"Tự mở khi kết nối",@"Auto start"),CPST(@"Đóng app cũ khi đổi khung",@"Close replaced apps"),CPST(@"Đóng app khi ngắt CarPlay",@"Close on disconnect")][p.row];key=@[@"autoStart",@"closeReplaced",@"closeDisconnect"][p.row];}
 if(p.section==2){c.textLabel.text=p.row==0?CPST(@"Ngôn ngữ",@"Language"):CPST(@"Cỡ chữ của Split",@"Split text size");c.detailTextLabel.text=p.row==0?CPST(@"Tiếng Việt",@"English"):@[CPST(@"Nhỏ",@"Small"),CPST(@"Vừa",@"Medium"),CPST(@"Lớn",@"Large")][MIN(2,MAX(0,[CPSPref(@"textSize") integerValue]))];}
 if(p.section==3){c.textLabel.text=@[CPST(@"Thông tin màn hình xe",@"Car display information"),CPST(@"Xuất log",@"Export logs"),CPST(@"Ghi hiệu năng",@"Record performance"),CPST(@"Xuất log hiệu năng",@"Export performance log"),CPST(@"Phiên bản",@"Version")][p.row];if(p.row==2)key=@"perfEnabled";if(p.row==4)c.detailTextLabel.text=@"0.3.0~alpha5test1";}
 if(key){UISwitch *s=[UISwitch new];s.accessibilityIdentifier=key;s.on=[key isEqual:@"enabled"]?CPSEnabled():[CPSPref(key) boolValue];[s addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventValueChanged];c.accessoryView=s;c.selectionStyle=UITableViewCellSelectionStyleNone;}
 else if(!(p.section==3&&p.row==4))c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;
}
- (void)toggle:(UISwitch *)s{CPSSetPref(s.accessibilityIdentifier,@(s.on));}
- (void)tableView:(UITableView *)v didSelectRowAtIndexPath:(NSIndexPath *)p{
 [v deselectRowAtIndexPath:p animated:YES];
 if(p.section==2){NSArray *labels=p.row==0?@[@"Tiếng Việt",@"English"]:@[CPST(@"Nhỏ",@"Small"),CPST(@"Vừa",@"Medium"),CPST(@"Lớn",@"Large")];UIAlertController *a=[UIAlertController alertControllerWithTitle:[v cellForRowAtIndexPath:p].textLabel.text message:nil preferredStyle:UIAlertControllerStyleActionSheet];for(NSUInteger i=0;i<labels.count;i++){[a addAction:[UIAlertAction actionWithTitle:labels[i] style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){CPSSetPref(p.row==0?@"language":@"textSize",p.row==0?(id)@[@"vi",@"en"][i]:@(i));[v reloadData];}]];}[a addAction:[UIAlertAction actionWithTitle:CPST(@"Hủy",@"Cancel") style:UIAlertActionStyleCancel handler:nil]];a.popoverPresentationController.sourceView=[v cellForRowAtIndexPath:p];[self presentViewController:a animated:YES completion:nil];return;}
 if(p.section==3&&p.row==0){NSString *info=CPSPref(@"displayInfo")?:CPST(@"Chưa ghi nhận kết nối CarPlay.",@"No CarPlay display recorded yet.");UIAlertController *a=[UIAlertController alertControllerWithTitle:CPST(@"Màn hình xe",@"Car display") message:info preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:0 handler:nil]];[self presentViewController:a animated:YES completion:nil];}
 if(p.section==3&&p.row==3){NSString *path=@"/var/mobile/Library/Logs/CarPlaySplit-performance.jsonl";if(![[NSFileManager defaultManager]fileExistsAtPath:path]){UIAlertController *a=[UIAlertController alertControllerWithTitle:CPST(@"Chưa có dữ liệu",@"No data yet") message:CPST(@"Bật ghi hiệu năng, mở Split trên CarPlay và thử thao tác trước.",@"Enable performance recording and exercise Split on CarPlay first.") preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];return;}UIActivityViewController *a=[[UIActivityViewController alloc]initWithActivityItems:@[[NSURL fileURLWithPath:path]] applicationActivities:nil];a.popoverPresentationController.sourceView=[v cellForRowAtIndexPath:p];[self presentViewController:a animated:YES completion:nil];}
 if(p.section==3&&p.row==1){NSString *path=@"/var/mobile/Library/Logs/CarPlaySplit-runtime.log";if(![[NSFileManager defaultManager]fileExistsAtPath:path]){UIAlertController *a=[UIAlertController alertControllerWithTitle:CPST(@"Chưa có log",@"No log yet") message:CPST(@"Kết nối CarPlay và mở Split để ghi log.",@"Connect CarPlay and open Split to record logs.") preferredStyle:1];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:0 handler:nil]];[self presentViewController:a animated:YES completion:nil];return;}UIActivityViewController *a=[[UIActivityViewController alloc]initWithActivityItems:@[[NSURL fileURLWithPath:path]] applicationActivities:nil];a.popoverPresentationController.sourceView=[v cellForRowAtIndexPath:p];[self presentViewController:a animated:YES completion:nil];}
}
@end
