include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CarPlayDSPPrefs
CarPlayDSPPrefs_FILES = CPDRootListController.m
CarPlayDSPPrefs_FRAMEWORKS = UIKit
CarPlayDSPPrefs_PRIVATE_FRAMEWORKS = Preferences
CarPlayDSPPrefs_INSTALL_PATH = /Library/PreferenceBundles
CarPlayDSPPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
